app:
    host: localhost
    port: 2021
    name: apiDoc-go
    runMode: release   # dev-开发模式 release-生产(正式)模式

mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: root
    charset: utf8mb4
    dbName: api-doc

log:
    directory: log
    showInConsole: true
    format: console  # json console

redis:
    enabled: false
    host: 127.0.0.1
    port: 6379
    user: 
    password: 
    dbId: 0
