// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 全局配置
type GlobalConf struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	Key       string    `gorm:"column:key;NOT NULL"`
	Value     string    `gorm:"column:value;NOT NULL"`
	CreatedAt time.Time `gorm:"column:created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at"`
	DeletedAt time.Time `gorm:"column:deleted_at"`
	Version   uint      `gorm:"column:version;default:0;NOT NULL"`
	CreatedBy uint64    `gorm:"column:created_by;default:0;NOT NULL"`
}

func (m *GlobalConf) TableName() string {
	return "global_conf"
}


